version: '3'

services:
    speedtest:
        build:
            context: .
        image: speedtest-for-influxdb-and-grafana
        container_name: speedtest
        volumes:
          - ./config.ini:/src/config.ini
        restart: always
